# Generated by Django 5.1.2 on 2025-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_user_delete_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_valid',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
