# Generated by Django 5.1.2 on 2025-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0009_formdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'verbose_name': 'Form Data', 'verbose_name_plural': 'Form Data'},
        ),
        migrations.AddField(
            model_name='formdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
