from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login_user'),
    path('register_user/', views.register_user, name='register_user'),
    path('userdashboard/', views.userdashboard, name='userdashboard'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('createprofile/', views.createprofile, name='createprofile'),
    path('updateprofile/', views.updateprofile, name='updateprofile'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('get_user_profile/', views.get_user_profile_api, name='get_user_profile'),
    path('get_all_profiles/', views.get_all_profiles, name='get_all_profiles'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('generate_otp/', views.generate_otp, name='generate_otp'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('otp_verification/', views.otp_verification, name='otp_verification'),
    path('logout/', views.logout, name='logout'),
    path('upload_resume/', views.upload_resume, name='upload_resume'),
    path('get_user_resumes/', views.get_user_resumes, name='get_user_resumes'),
    path('review_resume/<int:resume_id>/', views.review_resume, name='review_resume'),
    path('check_auth/', views.check_auth, name='check_auth'),
    path('save_selected_resume/', views.save_selected_resume, name='save_selected_resume'),
    path('delete_selected_resume/<int:resume_id>/', views.delete_selected_resume, name='delete_selected_resume'),
    path('get_selected_resumes/', views.get_selected_resumes, name='get_selected_resumes'),
    path('view_selected_resume/<int:resume_id>/', views.view_selected_resume, name='view_selected_resume'),
    path('list_selected_resumes/', views.list_selected_resumes, name='list_selected_resumes'),
    path('fill_form/', views.fill_form, name='fill_form'),
    path('get_users/', views.get_users, name='get_users'),
    path('get_user_selected_resumes/<int:user_id>/', views.get_user_selected_resumes, name='get_user_selected_resumes'),
    path('get_selected_resume_data/<int:resume_id>/', views.get_selected_resume_data, name='get_selected_resume_data'),
    path('save_form_data/', views.save_form_data, name='save_form_data'),
    path('get_all_resumes/', views.get_all_resumes, name='get_all_resumes'),
    path('delete_resume/<int:resume_id>/', views.delete_resume, name='delete_resume'),
    path('view_user_profile/<int:user_id>/', views.view_user_profile, name='view_user_profile'),
    path('view_resume/<int:resume_id>/', views.view_resume, name='view_resume'),
]